# Generated by Django 4.2.4 on 2023-09-16 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friends",
            name="account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.account"
            ),
        ),
        migrations.AddField(
            model_name="friends",
            name="archived",
            field=models.ManyToManyField(
                blank=True, db_index=True, related_name="archived_friends", to="users.account"
            ),
        ),
        migrations.AddField(
            model_name="friends",
            name="blocked",
            field=models.ManyToManyField(
                blank=True, db_index=True, related_name="blocked_friends", to="users.account"
            ),
        ),
        migrations.AddField(
            model_name="friends",
            name="followers",
            field=models.ManyToManyField(blank=True, db_index=True, related_name="my_followers", to="users.account"),
        ),
        migrations.AddField(
            model_name="friends",
            name="following",
            field=models.ManyToManyField(blank=True, db_index=True, related_name="Iam_following", to="users.account"),
        ),
        migrations.AddField(
            model_name="friends",
            name="new_request",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="community.friendrequest"
            ),
        ),
        migrations.AddField(
            model_name="friends",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receieved_friend_requests",
                to="users.account",
                verbose_name="receiver",
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="send_friend_requests",
                to="users.account",
                verbose_name="sender",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.account"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="members",
            field=models.ManyToManyField(
                blank=True, db_index=True, related_name="community_members", to="users.account"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
