# Generated by Django 4.2.4 on 2023-09-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_rename_community_communities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="status",
            field=models.CharField(
                choices=[("ACCEPT", "Accept"), ("PENDING", "Pending"), ("DECLINED", "Declined")],
                default="PENDING",
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="friends",
            name="new_request",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="community.friendrequest"
            ),
        ),
    ]
