# Generated by Django 4.2.4 on 2023-09-28 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_alter_friendrequest_status_alter_friends_new_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friends",
            name="new_request",
        ),
    ]
