# Generated by Django 4.2.4 on 2023-09-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0005_remove_friends_new_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="friends",
            name="relationship_type",
            field=models.CharField(
                choices=[("FOLLOWER", "Follower"), ("FOLLOWING", "Following"), ("NONE", "None")],
                default="NONE",
                max_length=50,
                verbose_name="relationship_type",
            ),
        ),
    ]
