# Generated by Django 4.2.4 on 2023-09-29 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0006_friends_relationship_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friends",
            name="relationship_type",
        ),
    ]
