# Generated by Django 4.2.4 on 2023-09-16 14:13

import argue_football.utilities.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityFeedBack",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=argue_football.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                ("comment", models.TextField(blank=True, db_index=True, null=True, verbose_name="Comment")),
                ("is_like", models.BooleanField(blank=True, default=False, null=True, verbose_name="Is_Like")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClubInterest",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=argue_football.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                (
                    "name",
                    models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name="club Name"),
                ),
                (
                    "league",
                    models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name="club League"),
                ),
                ("thumbnail", models.JSONField(blank=True, default=dict, null=True, verbose_name="Other Details")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=argue_football.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                (
                    "header",
                    models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name="Header"),
                ),
                ("body", models.TextField(blank=True, db_index=True, null=True, verbose_name="Body")),
                (
                    "thumbnail",
                    models.JSONField(blank=True, db_index=True, default=dict, null=True, verbose_name="Other Details"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostActivity",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=argue_football.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                ("comment", models.TextField(blank=True, db_index=True, null=True, verbose_name="Comment")),
                ("is_like", models.BooleanField(blank=True, default=False, null=True, verbose_name="Is_Like")),
                ("is_repost", models.BooleanField(blank=True, default=False, null=True, verbose_name="Is_Post")),
                ("is_bookmark", models.BooleanField(blank=True, default=False, null=True, verbose_name="Is_BookMark")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
