# Generated by Django 4.2.4 on 2023-09-16 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0002_initial"),
        ("users", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postactivity",
            name="account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.account"
            ),
        ),
        migrations.AddField(
            model_name="postactivity",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="postactivity",
            name="post",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posts.post"),
        ),
        migrations.AddField(
            model_name="post",
            name="account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.account"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="community_post",
                to="community.community",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="activityfeedback",
            name="account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.account"
            ),
        ),
        migrations.AddField(
            model_name="activityfeedback",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="activityfeedback",
            name="postactivity",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posts.postactivity"),
        ),
    ]
