# Generated by Django 4.2.4 on 2023-09-18 09:08

import argue_football.utilities.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("community", "0003_rename_community_communities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="shareable_link",
            field=models.URLField(db_index=True, default=1, unique=True, verbose_name="Shareable_Link"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.JSONField(blank=True, db_index=True, default=dict, null=True, verbose_name="Thumbnail"),
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=argue_football.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                (
                    "via",
                    models.CharField(
                        choices=[("DIRECT", "Direct"), ("COMMUNITY", "Community")],
                        db_index=True,
                        default="DIRECT",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "others",
                    models.CharField(
                        choices=[
                            ("WHATSAPP", "Whatsapp"),
                            ("INSTAGRAM", "Instagram"),
                            ("FACEBOOK", "Facebook"),
                            ("TWITTER", "Twitter"),
                        ],
                        db_index=True,
                        default="WHATSAPP",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.account"
                    ),
                ),
                (
                    "direct",
                    models.ManyToManyField(
                        blank=True, db_index=True, related_name="direct_sharing", to="community.friends"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="posts.post"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
