# Generated by Django 4.2.4 on 2023-09-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_rename_community_communities"),
        ("posts", "0003_post_shareable_link_alter_post_thumbnail_share"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="community",
        ),
        migrations.RemoveField(
            model_name="post",
            name="header",
        ),
        migrations.AddField(
            model_name="share",
            name="community",
            field=models.ManyToManyField(
                blank=True, db_index=True, related_name="community_sharing", to="community.communities"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(db_index=True, default=1, verbose_name="Body"),
            preserve_default=False,
        ),
    ]
