# Generated by Django 4.2.4 on 2023-09-18 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_remove_post_community_remove_post_header_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activityfeedback",
            name="comment",
        ),
        migrations.AddField(
            model_name="activityfeedback",
            name="response",
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name="Response"),
        ),
        migrations.AlterField(
            model_name="postactivity",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="post_engagements", to="posts.post"
            ),
        ),
    ]
