# Generated by Django 4.2.4 on 2023-09-23 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_remove_activityfeedback_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityfeedback",
            name="postactivity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedback", to="posts.postactivity"
            ),
        ),
        migrations.AlterField(
            model_name="postactivity",
            name="is_repost",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Is_Repost"),
        ),
    ]
