# Generated by Django 4.2.4 on 2023-09-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_activityfeedback_postactivity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="share",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="share_post",
                to="posts.post",
            ),
        ),
    ]
