# Generated by Django 4.2.4 on 2023-10-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("posts", "0007_alter_share_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="users.account",
            ),
        ),
    ]
